export const API_TYPES = {
  HealthController: Symbol.for("api.HealthController"),
  AuthController: Symbol.for("api.AuthController"),
  UsersController: Symbol.for("api.UsersController"),
  CampaignsController: Symbol.for("api.CampaignsController"),
  CampaignMembersController: Symbol.for("api.CampaignMembersController"),
  CampaignCharactersController: Symbol.for("api.CampaignCharactersController"),
  CampaignMonstersController: Symbol.for("api.CampaignMonstersController"),
  CampaignNpcsController: Symbol.for("api.CampaignNpcsController"),
  CampaignInventoryController: Symbol.for("api.CampaignInventoryController"),
  CampaignLocationsController: Symbol.for("api.CampaignLocationsController"),
  CampaignQuestsController: Symbol.for("api.CampaignQuestsController"),
  CampaignNotesController: Symbol.for("api.CampaignNotesController"),
  CampaignSessionsController: Symbol.for("api.CampaignSessionsController"),
  CampaignChronicleController: Symbol.for("api.CampaignChronicleController"),
  AuthMiddleware: Symbol.for("api.AuthMiddleware"),
  RequestContextMiddleware: Symbol.for("api.RequestContextMiddleware"),
  RequestLoggerMiddleware: Symbol.for("api.RequestLoggerMiddleware"),
  ErrorHandlerMiddleware: Symbol.for("api.ErrorHandlerMiddleware"),
} as const;
