export interface MonsterDetailsDTO {
  id: string;
  campaignId: string | null;
  name: string;
  slug: string;
  source: string;
  externalReferenceId: string | null;
  size: string | null;
  type: string | null;
  subtype: string | null;
  alignment: string | null;
  armorClass: number | null;
  armorClassDetails: string | null;
  hitPoints: number | null;
  hitDice: string | null;
  speed: unknown | null;
  abilities: {
    strength: number | null;
    dexterity: number | null;
    constitution: number | null;
    intelligence: number | null;
    wisdom: number | null;
    charisma: number | null;
  };
  savingThrows: unknown | null;
  skills: unknown | null;
  damageResistances: unknown | null;
  damageImmunities: unknown | null;
  conditionImmunities: unknown | null;
  damageVulnerabilities: unknown | null;
  senses: string | null;
  languages: string | null;
  challengeRating: string | null;
  challengeRatingDecimal: number | null;
  proficiencyBonus: number | null;
  xp: number | null;
  traits: unknown | null;
  actions: unknown | null;
  bonusActions: unknown | null;
  reactions: unknown | null;
  legendaryActions: unknown | null;
  lairActions: unknown | null;
  regionalEffects: unknown | null;
  spellcasting: unknown | null;
  description: string | null;
  sourceBook: string | null;
  pageNumber: string | null;
  visibility: string;
  status: string;
  customData: unknown | null;
  createdAt: string;
  updatedAt: string;
}
