import type { CharacterDetailsDTO } from "@modules/characters/application/dto/CharacterDetailsDTO";
import type { Character } from "@modules/characters/domain/entities/Character";

export function mapCharacterDetailsFromDomain(character: Character): CharacterDetailsDTO {
  return {
    id: character.id,
    campaignId: character.campaignId,
    ownerUserId: character.ownerUserId,
    sheetTemplateId: character.sheetTemplateId,
    name: character.name,
    avatarUrl: character.avatarUrl,
    type: character.type.value,
    status: character.status.value,
    race: character.race,
    characterClass: character.characterClass,
    subclass: character.subclass,
    level: character.level,
    background: character.background,
    alignment: character.alignment,
    experiencePoints: character.experiencePoints,
    armorClass: character.armorClass,
    initiativeBonus: character.initiativeBonus,
    speed: character.speed,
    maxHitPoints: character.maxHitPoints,
    currentHitPoints: character.currentHitPoints,
    temporaryHitPoints: character.temporaryHitPoints,
    hitDice: character.hitDice,
    strength: character.strength,
    dexterity: character.dexterity,
    constitution: character.constitution,
    intelligence: character.intelligence,
    wisdom: character.wisdom,
    charisma: character.charisma,
    proficiencyBonus: character.proficiencyBonus,
    savingThrows: character.savingThrows,
    skills: character.skills,
    proficiencies: character.proficiencies,
    languages: character.languages,
    attacksAndSpellcasting: character.attacksAndSpellcasting,
    spellcasting: character.spellcasting,
    featuresAndTraits: character.featuresAndTraits,
    personalityTraits: character.personalityTraits,
    ideals: character.ideals,
    bonds: character.bonds,
    flaws: character.flaws,
    backstory: character.backstory,
    appearance: character.appearance,
    customData: character.customData,
    createdAt: character.createdAt.toISOString(),
    updatedAt: character.updatedAt.toISOString(),
    deletedAt: character.deletedAt?.toISOString() ?? null,
  };
}
