export const appPaths = {
  campaign: (campaignId: string) => `/campaigns/${campaignId}`,
  campaignCharacters: (campaignId: string) => `/campaigns/${campaignId}/characters`,
  campaignCharactersRoute: "/campaigns/:campaignId/characters",
  campaignChronicle: (campaignId: string) => `/campaigns/${campaignId}/chronicle`,
  campaignChronicleRoute: "/campaigns/:campaignId/chronicle",
  campaignFightTracker: (campaignId: string) => `/campaigns/${campaignId}/fight-tracker`,
  campaignFightTrackerRoute: "/campaigns/:campaignId/fight-tracker",
  campaignInventory: (campaignId: string) => `/campaigns/${campaignId}/inventory`,
  campaignInventoryRoute: "/campaigns/:campaignId/inventory",
  campaignLocations: (campaignId: string) => `/campaigns/${campaignId}/locations`,
  campaignLocationsRoute: "/campaigns/:campaignId/locations",
  campaignMembers: (campaignId: string) => `/campaigns/${campaignId}/members`,
  campaignMembersRoute: "/campaigns/:campaignId/members",
  campaignMonsters: (campaignId: string) => `/campaigns/${campaignId}/monsters`,
  campaignMonstersRoute: "/campaigns/:campaignId/monsters",
  campaignNotes: (campaignId: string) => `/campaigns/${campaignId}/notes`,
  campaignNotesRoute: "/campaigns/:campaignId/notes",
  campaignNpcs: (campaignId: string) => `/campaigns/${campaignId}/npcs`,
  campaignNpcsRoute: "/campaigns/:campaignId/npcs",
  campaignOverview: "/campaigns/:campaignId",
  campaignQuests: (campaignId: string) => `/campaigns/${campaignId}/quests`,
  campaignQuestsRoute: "/campaigns/:campaignId/quests",
  campaignSessions: (campaignId: string) => `/campaigns/${campaignId}/sessions`,
  campaignSessionsRoute: "/campaigns/:campaignId/sessions",
  home: "/",
  items: "/items",
  login: "/login",
  monsters: "/monsters",
  notFound: "*",
  register: "/register",
  settings: "/settings",
} as const;
