export const QUESTS_TYPES = {
  QuestRepository: Symbol.for("quests.QuestRepository"),
  QuestReadRepository: Symbol.for("quests.QuestReadRepository"),
  QuestMapper: Symbol.for("quests.QuestMapper"),
  QuestVisibilityApplicationService: Symbol.for("quests.QuestVisibilityApplicationService"),
  QuestRelatedEntityApplicationService: Symbol.for("quests.QuestRelatedEntityApplicationService"),
  CreateQuestHandler: Symbol.for("quests.CreateQuestHandler"),
  UpdateQuestHandler: Symbol.for("quests.UpdateQuestHandler"),
  DeleteQuestHandler: Symbol.for("quests.DeleteQuestHandler"),
  ChangeQuestStatusHandler: Symbol.for("quests.ChangeQuestStatusHandler"),
  AddQuestObjectiveHandler: Symbol.for("quests.AddQuestObjectiveHandler"),
  UpdateQuestObjectiveHandler: Symbol.for("quests.UpdateQuestObjectiveHandler"),
  DeleteQuestObjectiveHandler: Symbol.for("quests.DeleteQuestObjectiveHandler"),
  LinkQuestEntityHandler: Symbol.for("quests.LinkQuestEntityHandler"),
  UnlinkQuestEntityHandler: Symbol.for("quests.UnlinkQuestEntityHandler"),
  ListCampaignQuestsHandler: Symbol.for("quests.ListCampaignQuestsHandler"),
  GetQuestDetailsHandler: Symbol.for("quests.GetQuestDetailsHandler"),
  ListQuestObjectivesHandler: Symbol.for("quests.ListQuestObjectivesHandler"),
} as const;
