import type { CampaignRole } from "@modules/campaigns/domain/value-objects/CampaignRole";
import { CAMPAIGN_ROLE, type CampaignRoleValue } from "@modules/campaigns/domain/value-objects/CampaignRole";

export const CAMPAIGN_PERMISSION_ACTION = {
  CAMPAIGN_READ: "campaign.read",
  CAMPAIGN_UPDATE: "campaign.update",
  CAMPAIGN_ARCHIVE: "campaign.archive",
  MEMBER_INVITE: "member.invite",
  MEMBER_REMOVE: "member.remove",
  MEMBER_CHANGE_ROLE: "member.change_role",
  CHARACTER_CREATE: "character.create",
  CHARACTER_READ: "character.read",
  CHARACTER_UPDATE: "character.update",
  CHARACTER_DELETE: "character.delete",
  NPC_CREATE: "npc.create",
  NPC_READ_SECRET: "npc.read_secret",
  NPC_UPDATE: "npc.update",
  NOTE_READ_PRIVATE_GM: "note.read_private_gm",
  NOTE_CREATE_PLAYER: "note.create_player",
  NOTE_MODERATE: "note.moderate",
  QUEST_READ_HIDDEN: "quest.read_hidden",
  QUEST_UPDATE: "quest.update",
  LOCATION_READ_HIDDEN: "location.read_hidden",
  LOCATION_UPDATE: "location.update",
  INVENTORY_TRANSFER: "inventory.transfer",
  SESSION_CREATE: "session.create",
  SESSION_UPDATE: "session.update",
  SESSION_COMPLETE: "session.complete",
} as const;

export type CampaignPermissionAction =
  (typeof CAMPAIGN_PERMISSION_ACTION)[keyof typeof CAMPAIGN_PERMISSION_ACTION];

const ALL_ACTIVE_MEMBER_ROLES = [
  CAMPAIGN_ROLE.OWNER,
  CAMPAIGN_ROLE.GM,
  CAMPAIGN_ROLE.CO_GM,
  CAMPAIGN_ROLE.PLAYER,
  CAMPAIGN_ROLE.OBSERVER,
] as const;

const CAMPAIGN_STAFF_ROLES = [
  CAMPAIGN_ROLE.OWNER,
  CAMPAIGN_ROLE.GM,
  CAMPAIGN_ROLE.CO_GM,
] as const;

const PLAYER_CONTRIBUTOR_ROLES = [
  CAMPAIGN_ROLE.OWNER,
  CAMPAIGN_ROLE.GM,
  CAMPAIGN_ROLE.CO_GM,
  CAMPAIGN_ROLE.PLAYER,
] as const;

const OWNER_ONLY_ROLES = [CAMPAIGN_ROLE.OWNER] as const;

const CAMPAIGN_PERMISSION_MATRIX: Record<CampaignPermissionAction, readonly CampaignRoleValue[]> = {
  [CAMPAIGN_PERMISSION_ACTION.CAMPAIGN_READ]: ALL_ACTIVE_MEMBER_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.CAMPAIGN_UPDATE]: OWNER_ONLY_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.CAMPAIGN_ARCHIVE]: OWNER_ONLY_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.MEMBER_INVITE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.MEMBER_REMOVE]: OWNER_ONLY_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.MEMBER_CHANGE_ROLE]: OWNER_ONLY_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.CHARACTER_CREATE]: PLAYER_CONTRIBUTOR_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.CHARACTER_READ]: ALL_ACTIVE_MEMBER_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.CHARACTER_UPDATE]: PLAYER_CONTRIBUTOR_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.CHARACTER_DELETE]: PLAYER_CONTRIBUTOR_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.NPC_CREATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.NPC_READ_SECRET]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.NPC_UPDATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.NOTE_READ_PRIVATE_GM]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.NOTE_CREATE_PLAYER]: PLAYER_CONTRIBUTOR_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.NOTE_MODERATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.QUEST_READ_HIDDEN]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.QUEST_UPDATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.LOCATION_READ_HIDDEN]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.LOCATION_UPDATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.INVENTORY_TRANSFER]: PLAYER_CONTRIBUTOR_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.SESSION_CREATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.SESSION_UPDATE]: CAMPAIGN_STAFF_ROLES,
  [CAMPAIGN_PERMISSION_ACTION.SESSION_COMPLETE]: CAMPAIGN_STAFF_ROLES,
};

export class CampaignPermissionDomainService {
  public can(role: CampaignRole, action: CampaignPermissionAction): boolean {
    return CAMPAIGN_PERMISSION_MATRIX[action].includes(role.value);
  }

  public canInviteRole(actorRole: CampaignRole, invitedRole: CampaignRole): boolean {
    if (!this.can(actorRole, CAMPAIGN_PERMISSION_ACTION.MEMBER_INVITE)) {
      return false;
    }

    if (invitedRole.value === CAMPAIGN_ROLE.OWNER) {
      return false;
    }

    if (invitedRole.canSeeFullCampaign()) {
      return actorRole.isOwner();
    }

    return true;
  }

  public canSeeSecretContent(role: CampaignRole): boolean {
    return this.can(role, CAMPAIGN_PERMISSION_ACTION.NOTE_READ_PRIVATE_GM);
  }
}
